#Addon release file

[CommandLevels]
$MAXCLIENTS=25
@NPCSPELLS=8
!setaaxp=100
!setaapts=100
!level=10
!damage=100
!heal=10
!npcspecialattk=100
!kill=100
!timeofday=80
!date=80
!haste=100
!weather=80
!shutdown=200
!setxp=100
!summonitem=0
!itemsearch=0
!finditem=0
!search=0
!spawn=10
!delacct=200
!size=80
!worldshutdown=200
!chat=200
!appearance=150
!zoneshutdown=150
!zonebootup=150
!emote=80
!summon=100
!kick=150
!mana=10
!npcloot=80
!findspell=20
!spfind=20
!castspell=20
!cast=20
!invul=80
!invulnerable=80
!setskill=20
!setskillall=20
!setallskill=20
!save=100
!depop=100
!depopcorpses=100
!depopzone=100
!repop=100
!spawnstatus=100
!listnpcs=100
!listnpccorpses=100
!listplayercorpses=100
!deletenpccorpses=100
!deleteplayercorpses=150
!showbuffs=100
!nukebuffs=100
!hideme=80
!deletecorpse=150
!sendzonespawns=200
!flymode=20
!race=20
!texture=10
!gender=10
!zheader=80
!zsky=80
!zcolor=80
!zcolour=80
!zuwcoords=100
!zsafecoords=100
!zclip=80
!zsave=200
!npccast=80
!dbspawn2=200
!npctypespawn=10
!attack=150
!zstats=80
!lock=150
!unlock=150
!motd=150
!makepet=20
!crashtest=201
!showpetspell=250
!freeze=100
!unfreeze=100
!pvp=100
!permaclass=80
!permarace=80
!permagender=80
!gm=100
!gmspeed=100
!movechar=100
!title=100
!copychar=200
!serverinfo=201
!npcstats=80
!memspell=100
!zone=10
