#linux threads flags:
LTFLAGS=-I/usr/local/include/pthread/linuxthreads -D_GNU_SOURCE -D__USE_UNIX98 -D_REENTRANT -D_THREAD_SAFE
LTLDFLAGS=-llthread -llstdc++ -llsupc++ -llgcc_r -L/usr/local/lib

CXXFLAGS=-ggdb -O -pipe -Wall -I../common -DCOLLECTOR -DFREEBSD $(LTFLAGS)
LDFLAGS=-lpcap -lz -rdynamic -O2 -ggdb -pipe $(LTLDFLAGS)

all: eqemucollector plugins

include .depend

include Makefile.common

.depend depend:
	echo $(OBJS) "" | sed -e 's#.obj/#../common/#g' -e 's/\.o/.cpp/g' | \
	xargs mkdep $(CXXFLAGS)


