#the set of objects needed to do something useful with packetfiles
PFOBJS=.obj/Mutex.o .obj/unix.o .obj/packetfile.o \
  .obj/opcodemgr.o ../common/emu_opcodes.o

#objects for EQ extractor
EEOBJS=eqextractor.o $(PFOBJS) ../common/dbcore.o ExtractCollector.o \
  ExtractDB.o ../common/MiscFunctions.o Explorers.o ../common/misc.o \
  StructExplorer.o ../common/packet_dump.o ../common/buildfile.o \
  patches/versions.o patches/patch_021505.o patches/patch_current.o \
  patches/patch_local.o patches/patch_121504.o patches/patch_051105.o \
  patches/patch_Titanium.o patches/patch_62.o patches/patch_Anniversary.o 

all: eqextractor pf2text catalogpf restamppf

pf2text: pf2text.o $(PFOBJS) ../common/eqstrmgr.o
	g++ $(LDFLAGS) -o $@ $^

catalogpf: catalogpf.o $(PFOBJS)
	g++ $(LDFLAGS) -o $@ $^

restamppf: restamppf.o $(PFOBJS)
	g++ $(LDFLAGS) -o $@ $^

eqextractor: $(EEOBJS)
	g++ $^ $(LDFLAGS) $(MYSQL_LIBS) -o $@ 

#force these to depend on the oplist
../common/emu_opcodes.o: ../common/emu_oplist.h
.obj/opcodemgr.o: ../common/emu_oplist.h

clean:
	rm -f eqextract $(EEOBJS) $(PFOBJS) eqextractor pf2text pf2text.o

.obj/%.o: ../common/%.cpp ../common/%.h
	mkdir -p .obj
	$(CC) $(CXXFLAGS) -c $< -o $@

%.o: %.cpp %.h
	mkdir -p .obj
	$(CC) $(CXXFLAGS) -c $< -o $@


