#!/bin/sh

if [ ! -h ./miniperl ]; then
	echo "You must have a link in this dir to perl named ./miniperl"
	exit 1
fi

./convert client.h Client
./convert entity.h EntityList
./convert mob.h Mob
./convert npc.h NPC
./convert PlayerCorpse.h Corpse
./convert groups.h Group
