APP=zone
#the non-perl zone can still compile and link all the perl objects
#because they are all #ifdef'd out anyways..
SF= .obj/EQPacket.o .obj/EQStream.o .obj/EQStreamFactory.o .obj/CRC16.o \
   ../common/timer.o  ../common/packet_dump.o ../common/packet_functions.o \
   ../common/unix.o ../common/packet_dump_file.o ../common/Mutex.o ../common/MiscFunctions.o \
   zone.o entity.o mob.o client.o client_process.o npc.o net.o spawn2.o attack.o hate_list.o \
   ../common/serverinfo.o ../common/moremath.o worldserver.o spells.o spawngroup.o loottables.o \
   faction.o Map.o PlayerCorpse.o petitions.o MobAI.o Object.o ../common/eqtime.o \
   groups.o ../common/classes.o ../common/races.o ../common/TCPConnection.o forage.o \
   ../common/crc32.o ../common/guilds.o ../common/md5.o ../common/dbcore.o \
   ../common/dbasync.o zonedbasync.o parser.o embperl.o embparser.o \
   ../common/EMuShareMem.o ../common/EQEMuError.o ../common/ptimer.o \
   .obj/debug.o .obj/database.o .obj/Item.o .obj/misc.o tribute.o \
   doors.o command.o beacon.o embxs.o AA.o trap.o client_packet.o \
   bonuses.o trading.o spdat.o  spell_effects.o aggro.o guilds.o \
   inventory.o client_mods.o tradeskills.o waypoints.o pets.o zone_profile.o \
   effects.o perl_client.o perl_entity.o perl_mob.o perl_npc.o \
   perl_PlayerCorpse.o perl_groups.o questmgr.o client_logs.o perlparser.o \
   ../common/rdtsc.o ../common/extprofile.o horse.o exp.o pathing.o \
   fearpath.o special_attacks.o ../common/timeoutmgr.o ../common/Condition.o \
   .obj/opcodemgr.o .obj/emu_opcodes.o ../common/SharedLibrary.o zoning.o \
   titles.o


all: $(APP)


$(APP): $(SF)
	$(LINKER) $(COPTS) $(OBJS) $^ $(LINKOPTS) `$(PERL_LIB)` -o $@


import_raw_items: import_raw_items.o
	$(LINKER) $(COPTS) $^ $(LINKOPTS) `$(PERL_LIB)` -o $@

clean:
	rm -f $(SF) $(APP) import_raw_items.o import_raw_items

%.o: %.cpp
	$(CC) -c $(COPTS) `$(PERL_FLAGS)` $< -o $@

.obj/%.o: ../common/%.cpp ../common/%.h
	mkdir -p .obj
	$(CC) $(COPTS) -c $< -o $@

