/*
 * This file was generated automatically by xsubpp version 1.9508 from the
 * contents of tmp. Do not edit this file, edit tmp instead.
 *
 *		ANY CHANGES MADE HERE WILL BE LOST!
 *
 */


/*  EQEMu:  Everquest Server Emulator
	Copyright (C) 2001-2004  EQEMu Development Team (http://eqemulator.net)

	This program is free software; you can redistribute it and/or modify
	it under the terms of the GNU General Public License as published by
	the Free Software Foundation; version 2 of the License.

	This program is distributed in the hope that it will be useful,
	but WITHOUT ANY WARRANTY except by those people which sell it, which
		are required to give you total support for your newly bought product;
		without even the implied warranty of MERCHANTABILITY or FITNESS FOR
		A PARTICULAR PURPOSE.  See the GNU General Public License for more details.

	You should have received a copy of the GNU General Public License
	along with this program; if not, write to the Free Software
	Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
*/

#include "features.h"
#ifdef EMBPERL_XS_CLASSES
#include "embperl.h"
#include "../common/debug.h"

typedef const char Const_char;

#include "npc.h"
#include "../common/debug.h"

XS(XS_NPC_CheckNPCFactionAlly); /* prototype to pass -Wmissing-prototypes */
XS(XS_NPC_CheckNPCFactionAlly)
{
	dXSARGS;
	if (items != 2)
		Perl_croak(aTHX_ "Usage: NPC::CheckNPCFactionAlly(THIS, other_faction)");
	{
		NPC *		THIS;
		FACTION_VALUE		RETVAL;
		dXSTARG;
		sint32		other_faction = (sint32)SvIV(ST(1));

		if (sv_derived_from(ST(0), "NPC")) {
			IV tmp = SvIV((SV*)SvRV(ST(0)));
			THIS = INT2PTR(NPC *,tmp);
		}
		else
			Perl_croak(aTHX_ "THIS is not of type NPC");

		RETVAL = THIS->CheckNPCFactionAlly(other_faction);
		XSprePUSH; PUSHi((IV)RETVAL);
	}
	XSRETURN(1);
}

XS(XS_NPC_GetReverseFactionCon); /* prototype to pass -Wmissing-prototypes */
XS(XS_NPC_GetReverseFactionCon)
{
	dXSARGS;
	if (items != 2)
		Perl_croak(aTHX_ "Usage: NPC::GetReverseFactionCon(THIS, iOther)");
	{
		NPC *		THIS;
		FACTION_VALUE		RETVAL;
		dXSTARG;
		Mob*		iOther;

		if (sv_derived_from(ST(0), "NPC")) {
			IV tmp = SvIV((SV*)SvRV(ST(0)));
			THIS = INT2PTR(NPC *,tmp);
		}
		else
			Perl_croak(aTHX_ "THIS is not of type NPC");

		if (sv_derived_from(ST(1), "Mob")) {
			IV tmp = SvIV((SV*)SvRV(ST(1)));
			iOther = INT2PTR(Mob *,tmp);
		}
		else
			Perl_croak(aTHX_ "iOther is not of type Mob");

		RETVAL = THIS->GetReverseFactionCon(iOther);
		XSprePUSH; PUSHi((IV)RETVAL);
	}
	XSRETURN(1);
}

XS(XS_NPC_GoToBind); /* prototype to pass -Wmissing-prototypes */
XS(XS_NPC_GoToBind)
{
	dXSARGS;
	if (items != 1)
		Perl_croak(aTHX_ "Usage: NPC::GoToBind(THIS)");
	{
		NPC *		THIS;

		if (sv_derived_from(ST(0), "NPC")) {
			IV tmp = SvIV((SV*)SvRV(ST(0)));
			THIS = INT2PTR(NPC *,tmp);
		}
		else
			Perl_croak(aTHX_ "THIS is not of type NPC");

		THIS->GoToBind();
	}
	XSRETURN_EMPTY;
}

XS(XS_NPC_AddItem); /* prototype to pass -Wmissing-prototypes */
XS(XS_NPC_AddItem)
{
	dXSARGS;
	if (items < 3 || items > 4)
		Perl_croak(aTHX_ "Usage: NPC::AddItem(THIS, itemid, charges, slot= 0)");
	{
		NPC *		THIS;
		int32		itemid = (int32)SvUV(ST(1));
		int8		charges = (int8)SvUV(ST(2));
		int8		slot;

		if (sv_derived_from(ST(0), "NPC")) {
			IV tmp = SvIV((SV*)SvRV(ST(0)));
			THIS = INT2PTR(NPC *,tmp);
		}
		else
			Perl_croak(aTHX_ "THIS is not of type NPC");

		if (items < 4)
			slot = 0;
		else {
			slot = (int8)SvUV(ST(3));
		}

		THIS->AddItem(itemid, charges, slot);
	}
	XSRETURN_EMPTY;
}

XS(XS_NPC_AddLootTable); /* prototype to pass -Wmissing-prototypes */
XS(XS_NPC_AddLootTable)
{
	dXSARGS;
	if (items != 1)
		Perl_croak(aTHX_ "Usage: NPC::AddLootTable(THIS)");
	{
		NPC *		THIS;

		if (sv_derived_from(ST(0), "NPC")) {
			IV tmp = SvIV((SV*)SvRV(ST(0)));
			THIS = INT2PTR(NPC *,tmp);
		}
		else
			Perl_croak(aTHX_ "THIS is not of type NPC");

		THIS->AddLootTable();
	}
	XSRETURN_EMPTY;
}

XS(XS_NPC_IsRanger); /* prototype to pass -Wmissing-prototypes */
XS(XS_NPC_IsRanger)
{
	dXSARGS;
	if (items != 1)
		Perl_croak(aTHX_ "Usage: NPC::IsRanger(THIS)");
	{
		NPC *		THIS;
		bool		RETVAL;

		if (sv_derived_from(ST(0), "NPC")) {
			IV tmp = SvIV((SV*)SvRV(ST(0)));
			THIS = INT2PTR(NPC *,tmp);
		}
		else
			Perl_croak(aTHX_ "THIS is not of type NPC");

		RETVAL = THIS->IsRanger();
		ST(0) = boolSV(RETVAL);
		sv_2mortal(ST(0));
	}
	XSRETURN(1);
}

XS(XS_NPC_RemoveItem); /* prototype to pass -Wmissing-prototypes */
XS(XS_NPC_RemoveItem)
{
	dXSARGS;
	if (items < 2 || items > 4)
		Perl_croak(aTHX_ "Usage: NPC::RemoveItem(THIS, item_id, quantity= 0, slot= 0)");
	{
		NPC *		THIS;
		uint16		item_id = (uint16)SvUV(ST(1));
		int16		quantity;
		int16		slot;

		if (sv_derived_from(ST(0), "NPC")) {
			IV tmp = SvIV((SV*)SvRV(ST(0)));
			THIS = INT2PTR(NPC *,tmp);
		}
		else
			Perl_croak(aTHX_ "THIS is not of type NPC");

		if (items < 3)
			quantity = 0;
		else {
			quantity = (int16)SvUV(ST(2));
		}

		if (items < 4)
			slot = 0;
		else {
			slot = (int16)SvUV(ST(3));
		}

		THIS->RemoveItem(item_id, quantity, slot);
	}
	XSRETURN_EMPTY;
}

XS(XS_NPC_ClearItemList); /* prototype to pass -Wmissing-prototypes */
XS(XS_NPC_ClearItemList)
{
	dXSARGS;
	if (items != 1)
		Perl_croak(aTHX_ "Usage: NPC::ClearItemList(THIS)");
	{
		NPC *		THIS;

		if (sv_derived_from(ST(0), "NPC")) {
			IV tmp = SvIV((SV*)SvRV(ST(0)));
			THIS = INT2PTR(NPC *,tmp);
		}
		else
			Perl_croak(aTHX_ "THIS is not of type NPC");

		THIS->ClearItemList();
	}
	XSRETURN_EMPTY;
}

XS(XS_NPC_AddCash); /* prototype to pass -Wmissing-prototypes */
XS(XS_NPC_AddCash)
{
	dXSARGS;
	if (items != 5)
		Perl_croak(aTHX_ "Usage: NPC::AddCash(THIS, in_copper, in_silver, in_gold, in_platinum)");
	{
		NPC *		THIS;
		int16		in_copper = (int16)SvUV(ST(1));
		int16		in_silver = (int16)SvUV(ST(2));
		int16		in_gold = (int16)SvUV(ST(3));
		int16		in_platinum = (int16)SvUV(ST(4));

		if (sv_derived_from(ST(0), "NPC")) {
			IV tmp = SvIV((SV*)SvRV(ST(0)));
			THIS = INT2PTR(NPC *,tmp);
		}
		else
			Perl_croak(aTHX_ "THIS is not of type NPC");

		THIS->AddCash(in_copper, in_silver, in_gold, in_platinum);
	}
	XSRETURN_EMPTY;
}

XS(XS_NPC_RemoveCash); /* prototype to pass -Wmissing-prototypes */
XS(XS_NPC_RemoveCash)
{
	dXSARGS;
	if (items != 1)
		Perl_croak(aTHX_ "Usage: NPC::RemoveCash(THIS)");
	{
		NPC *		THIS;

		if (sv_derived_from(ST(0), "NPC")) {
			IV tmp = SvIV((SV*)SvRV(ST(0)));
			THIS = INT2PTR(NPC *,tmp);
		}
		else
			Perl_croak(aTHX_ "THIS is not of type NPC");

		THIS->RemoveCash();
	}
	XSRETURN_EMPTY;
}

XS(XS_NPC_CountLoot); /* prototype to pass -Wmissing-prototypes */
XS(XS_NPC_CountLoot)
{
	dXSARGS;
	if (items != 1)
		Perl_croak(aTHX_ "Usage: NPC::CountLoot(THIS)");
	{
		NPC *		THIS;
		int32		RETVAL;
		dXSTARG;

		if (sv_derived_from(ST(0), "NPC")) {
			IV tmp = SvIV((SV*)SvRV(ST(0)));
			THIS = INT2PTR(NPC *,tmp);
		}
		else
			Perl_croak(aTHX_ "THIS is not of type NPC");

		RETVAL = THIS->CountLoot();
		XSprePUSH; PUSHu((UV)RETVAL);
	}
	XSRETURN(1);
}

XS(XS_NPC_GetLoottableID); /* prototype to pass -Wmissing-prototypes */
XS(XS_NPC_GetLoottableID)
{
	dXSARGS;
	if (items != 1)
		Perl_croak(aTHX_ "Usage: NPC::GetLoottableID(THIS)");
	{
		NPC *		THIS;
		int32		RETVAL;
		dXSTARG;

		if (sv_derived_from(ST(0), "NPC")) {
			IV tmp = SvIV((SV*)SvRV(ST(0)));
			THIS = INT2PTR(NPC *,tmp);
		}
		else
			Perl_croak(aTHX_ "THIS is not of type NPC");

		RETVAL = THIS->GetLoottableID();
		XSprePUSH; PUSHu((UV)RETVAL);
	}
	XSRETURN(1);
}

XS(XS_NPC_SetPetType); /* prototype to pass -Wmissing-prototypes */
XS(XS_NPC_SetPetType)
{
	dXSARGS;
	if (items != 2)
		Perl_croak(aTHX_ "Usage: NPC::SetPetType(THIS, in_type)");
	{
		NPC *		THIS;
		int16		in_type = (int16)SvUV(ST(1));

		if (sv_derived_from(ST(0), "NPC")) {
			IV tmp = SvIV((SV*)SvRV(ST(0)));
			THIS = INT2PTR(NPC *,tmp);
		}
		else
			Perl_croak(aTHX_ "THIS is not of type NPC");

		THIS->SetPetType(in_type);
	}
	XSRETURN_EMPTY;
}

XS(XS_NPC_GetCopper); /* prototype to pass -Wmissing-prototypes */
XS(XS_NPC_GetCopper)
{
	dXSARGS;
	if (items != 1)
		Perl_croak(aTHX_ "Usage: NPC::GetCopper(THIS)");
	{
		NPC *		THIS;
		uint32		RETVAL;
		dXSTARG;

		if (sv_derived_from(ST(0), "NPC")) {
			IV tmp = SvIV((SV*)SvRV(ST(0)));
			THIS = INT2PTR(NPC *,tmp);
		}
		else
			Perl_croak(aTHX_ "THIS is not of type NPC");

		RETVAL = THIS->GetCopper();
		XSprePUSH; PUSHu((UV)RETVAL);
	}
	XSRETURN(1);
}

XS(XS_NPC_GetSilver); /* prototype to pass -Wmissing-prototypes */
XS(XS_NPC_GetSilver)
{
	dXSARGS;
	if (items != 1)
		Perl_croak(aTHX_ "Usage: NPC::GetSilver(THIS)");
	{
		NPC *		THIS;
		uint32		RETVAL;
		dXSTARG;

		if (sv_derived_from(ST(0), "NPC")) {
			IV tmp = SvIV((SV*)SvRV(ST(0)));
			THIS = INT2PTR(NPC *,tmp);
		}
		else
			Perl_croak(aTHX_ "THIS is not of type NPC");

		RETVAL = THIS->GetSilver();
		XSprePUSH; PUSHu((UV)RETVAL);
	}
	XSRETURN(1);
}

XS(XS_NPC_GetGold); /* prototype to pass -Wmissing-prototypes */
XS(XS_NPC_GetGold)
{
	dXSARGS;
	if (items != 1)
		Perl_croak(aTHX_ "Usage: NPC::GetGold(THIS)");
	{
		NPC *		THIS;
		uint32		RETVAL;
		dXSTARG;

		if (sv_derived_from(ST(0), "NPC")) {
			IV tmp = SvIV((SV*)SvRV(ST(0)));
			THIS = INT2PTR(NPC *,tmp);
		}
		else
			Perl_croak(aTHX_ "THIS is not of type NPC");

		RETVAL = THIS->GetGold();
		XSprePUSH; PUSHu((UV)RETVAL);
	}
	XSRETURN(1);
}

XS(XS_NPC_GetPlatinum); /* prototype to pass -Wmissing-prototypes */
XS(XS_NPC_GetPlatinum)
{
	dXSARGS;
	if (items != 1)
		Perl_croak(aTHX_ "Usage: NPC::GetPlatinum(THIS)");
	{
		NPC *		THIS;
		uint32		RETVAL;
		dXSTARG;

		if (sv_derived_from(ST(0), "NPC")) {
			IV tmp = SvIV((SV*)SvRV(ST(0)));
			THIS = INT2PTR(NPC *,tmp);
		}
		else
			Perl_croak(aTHX_ "THIS is not of type NPC");

		RETVAL = THIS->GetPlatinum();
		XSprePUSH; PUSHu((UV)RETVAL);
	}
	XSRETURN(1);
}

XS(XS_NPC_SetCopper); /* prototype to pass -Wmissing-prototypes */
XS(XS_NPC_SetCopper)
{
	dXSARGS;
	if (items != 2)
		Perl_croak(aTHX_ "Usage: NPC::SetCopper(THIS, amt)");
	{
		NPC *		THIS;
		uint32		amt = (uint32)SvUV(ST(1));

		if (sv_derived_from(ST(0), "NPC")) {
			IV tmp = SvIV((SV*)SvRV(ST(0)));
			THIS = INT2PTR(NPC *,tmp);
		}
		else
			Perl_croak(aTHX_ "THIS is not of type NPC");

		THIS->SetCopper(amt);
	}
	XSRETURN_EMPTY;
}

XS(XS_NPC_SetSilver); /* prototype to pass -Wmissing-prototypes */
XS(XS_NPC_SetSilver)
{
	dXSARGS;
	if (items != 2)
		Perl_croak(aTHX_ "Usage: NPC::SetSilver(THIS, amt)");
	{
		NPC *		THIS;
		uint32		amt = (uint32)SvUV(ST(1));

		if (sv_derived_from(ST(0), "NPC")) {
			IV tmp = SvIV((SV*)SvRV(ST(0)));
			THIS = INT2PTR(NPC *,tmp);
		}
		else
			Perl_croak(aTHX_ "THIS is not of type NPC");

		THIS->SetSilver(amt);
	}
	XSRETURN_EMPTY;
}

XS(XS_NPC_SetGold); /* prototype to pass -Wmissing-prototypes */
XS(XS_NPC_SetGold)
{
	dXSARGS;
	if (items != 2)
		Perl_croak(aTHX_ "Usage: NPC::SetGold(THIS, amt)");
	{
		NPC *		THIS;
		uint32		amt = (uint32)SvUV(ST(1));

		if (sv_derived_from(ST(0), "NPC")) {
			IV tmp = SvIV((SV*)SvRV(ST(0)));
			THIS = INT2PTR(NPC *,tmp);
		}
		else
			Perl_croak(aTHX_ "THIS is not of type NPC");

		THIS->SetGold(amt);
	}
	XSRETURN_EMPTY;
}

XS(XS_NPC_SetPlatinum); /* prototype to pass -Wmissing-prototypes */
XS(XS_NPC_SetPlatinum)
{
	dXSARGS;
	if (items != 2)
		Perl_croak(aTHX_ "Usage: NPC::SetPlatinum(THIS, amt)");
	{
		NPC *		THIS;
		uint32		amt = (uint32)SvUV(ST(1));

		if (sv_derived_from(ST(0), "NPC")) {
			IV tmp = SvIV((SV*)SvRV(ST(0)));
			THIS = INT2PTR(NPC *,tmp);
		}
		else
			Perl_croak(aTHX_ "THIS is not of type NPC");

		THIS->SetPlatinum(amt);
	}
	XSRETURN_EMPTY;
}

XS(XS_NPC_SetGrid); /* prototype to pass -Wmissing-prototypes */
XS(XS_NPC_SetGrid)
{
	dXSARGS;
	if (items != 2)
		Perl_croak(aTHX_ "Usage: NPC::SetGrid(THIS, grid_)");
	{
		NPC *		THIS;
		int16		grid_ = (int16)SvUV(ST(1));

		if (sv_derived_from(ST(0), "NPC")) {
			IV tmp = SvIV((SV*)SvRV(ST(0)));
			THIS = INT2PTR(NPC *,tmp);
		}
		else
			Perl_croak(aTHX_ "THIS is not of type NPC");

		THIS->SetGrid(grid_);
	}
	XSRETURN_EMPTY;
}

XS(XS_NPC_SetSp2); /* prototype to pass -Wmissing-prototypes */
XS(XS_NPC_SetSp2)
{
	dXSARGS;
	if (items != 2)
		Perl_croak(aTHX_ "Usage: NPC::SetSp2(THIS, sg2)");
	{
		NPC *		THIS;
		int32		sg2 = (int32)SvUV(ST(1));

		if (sv_derived_from(ST(0), "NPC")) {
			IV tmp = SvIV((SV*)SvRV(ST(0)));
			THIS = INT2PTR(NPC *,tmp);
		}
		else
			Perl_croak(aTHX_ "THIS is not of type NPC");

		THIS->SetSp2(sg2);
	}
	XSRETURN_EMPTY;
}

XS(XS_NPC_GetWaypointMax); /* prototype to pass -Wmissing-prototypes */
XS(XS_NPC_GetWaypointMax)
{
	dXSARGS;
	if (items != 1)
		Perl_croak(aTHX_ "Usage: NPC::GetWaypointMax(THIS)");
	{
		NPC *		THIS;
		int16		RETVAL;
		dXSTARG;

		if (sv_derived_from(ST(0), "NPC")) {
			IV tmp = SvIV((SV*)SvRV(ST(0)));
			THIS = INT2PTR(NPC *,tmp);
		}
		else
			Perl_croak(aTHX_ "THIS is not of type NPC");

		RETVAL = THIS->GetWaypointMax();
		XSprePUSH; PUSHu((UV)RETVAL);
	}
	XSRETURN(1);
}

XS(XS_NPC_GetGrid); /* prototype to pass -Wmissing-prototypes */
XS(XS_NPC_GetGrid)
{
	dXSARGS;
	if (items != 1)
		Perl_croak(aTHX_ "Usage: NPC::GetGrid(THIS)");
	{
		NPC *		THIS;
		sint16		RETVAL;
		dXSTARG;

		if (sv_derived_from(ST(0), "NPC")) {
			IV tmp = SvIV((SV*)SvRV(ST(0)));
			THIS = INT2PTR(NPC *,tmp);
		}
		else
			Perl_croak(aTHX_ "THIS is not of type NPC");

		RETVAL = THIS->GetGrid();
		XSprePUSH; PUSHi((IV)RETVAL);
	}
	XSRETURN(1);
}

XS(XS_NPC_GetSp2); /* prototype to pass -Wmissing-prototypes */
XS(XS_NPC_GetSp2)
{
	dXSARGS;
	if (items != 1)
		Perl_croak(aTHX_ "Usage: NPC::GetSp2(THIS)");
	{
		NPC *		THIS;
		int32		RETVAL;
		dXSTARG;

		if (sv_derived_from(ST(0), "NPC")) {
			IV tmp = SvIV((SV*)SvRV(ST(0)));
			THIS = INT2PTR(NPC *,tmp);
		}
		else
			Perl_croak(aTHX_ "THIS is not of type NPC");

		RETVAL = THIS->GetSp2();
		XSprePUSH; PUSHu((UV)RETVAL);
	}
	XSRETURN(1);
}

XS(XS_NPC_Depop); /* prototype to pass -Wmissing-prototypes */
XS(XS_NPC_Depop)
{
	dXSARGS;
	if (items < 1 || items > 2)
		Perl_croak(aTHX_ "Usage: NPC::Depop(THIS, StartSpawnTimer= true)");
	{
		NPC *		THIS;
		bool		StartSpawnTimer;

		if (sv_derived_from(ST(0), "NPC")) {
			IV tmp = SvIV((SV*)SvRV(ST(0)));
			THIS = INT2PTR(NPC *,tmp);
		}
		else
			Perl_croak(aTHX_ "THIS is not of type NPC");

		if (items < 2)
			StartSpawnTimer = true;
		else {
			StartSpawnTimer = (bool)SvTRUE(ST(1));
		}

		THIS->Depop(StartSpawnTimer);
	}
	XSRETURN_EMPTY;
}

XS(XS_NPC_Stun); /* prototype to pass -Wmissing-prototypes */
XS(XS_NPC_Stun)
{
	dXSARGS;
	if (items != 2)
		Perl_croak(aTHX_ "Usage: NPC::Stun(THIS, duration)");
	{
		NPC *		THIS;
		int		duration = (int)SvIV(ST(1));

		if (sv_derived_from(ST(0), "NPC")) {
			IV tmp = SvIV((SV*)SvRV(ST(0)));
			THIS = INT2PTR(NPC *,tmp);
		}
		else
			Perl_croak(aTHX_ "THIS is not of type NPC");

		THIS->Stun(duration);
	}
	XSRETURN_EMPTY;
}

XS(XS_NPC_IsStunned); /* prototype to pass -Wmissing-prototypes */
XS(XS_NPC_IsStunned)
{
	dXSARGS;
	if (items != 1)
		Perl_croak(aTHX_ "Usage: NPC::IsStunned(THIS)");
	{
		NPC *		THIS;
		bool		RETVAL;

		if (sv_derived_from(ST(0), "NPC")) {
			IV tmp = SvIV((SV*)SvRV(ST(0)));
			THIS = INT2PTR(NPC *,tmp);
		}
		else
			Perl_croak(aTHX_ "THIS is not of type NPC");

		RETVAL = THIS->IsStunned();
		ST(0) = boolSV(RETVAL);
		sv_2mortal(ST(0));
	}
	XSRETURN(1);
}

XS(XS_NPC_IsPVP); /* prototype to pass -Wmissing-prototypes */
XS(XS_NPC_IsPVP)
{
	dXSARGS;
	if (items != 1)
		Perl_croak(aTHX_ "Usage: NPC::IsPVP(THIS)");
	{
		NPC *		THIS;
		bool		RETVAL;

		if (sv_derived_from(ST(0), "NPC")) {
			IV tmp = SvIV((SV*)SvRV(ST(0)));
			THIS = INT2PTR(NPC *,tmp);
		}
		else
			Perl_croak(aTHX_ "THIS is not of type NPC");

		RETVAL = THIS->IsPVP();
		ST(0) = boolSV(RETVAL);
		sv_2mortal(ST(0));
	}
	XSRETURN(1);
}

XS(XS_NPC_CurrentPosition); /* prototype to pass -Wmissing-prototypes */
XS(XS_NPC_CurrentPosition)
{
	dXSARGS;
	if (items != 1)
		Perl_croak(aTHX_ "Usage: NPC::CurrentPosition(THIS)");
	{
		NPC *		THIS;
		int8		RETVAL;
		dXSTARG;

		if (sv_derived_from(ST(0), "NPC")) {
			IV tmp = SvIV((SV*)SvRV(ST(0)));
			THIS = INT2PTR(NPC *,tmp);
		}
		else
			Perl_croak(aTHX_ "THIS is not of type NPC");

		RETVAL = THIS->CurrentPosition();
		XSprePUSH; PUSHu((UV)RETVAL);
	}
	XSRETURN(1);
}

XS(XS_NPC_HasBanishCapability); /* prototype to pass -Wmissing-prototypes */
XS(XS_NPC_HasBanishCapability)
{
	dXSARGS;
	if (items != 1)
		Perl_croak(aTHX_ "Usage: NPC::HasBanishCapability(THIS)");
	{
		NPC *		THIS;
		int8		RETVAL;
		dXSTARG;

		if (sv_derived_from(ST(0), "NPC")) {
			IV tmp = SvIV((SV*)SvRV(ST(0)));
			THIS = INT2PTR(NPC *,tmp);
		}
		else
			Perl_croak(aTHX_ "THIS is not of type NPC");

		RETVAL = THIS->HasBanishCapability();
		XSprePUSH; PUSHu((UV)RETVAL);
	}
	XSRETURN(1);
}

XS(XS_NPC_GetNPCFactionID); /* prototype to pass -Wmissing-prototypes */
XS(XS_NPC_GetNPCFactionID)
{
	dXSARGS;
	if (items != 1)
		Perl_croak(aTHX_ "Usage: NPC::GetNPCFactionID(THIS)");
	{
		NPC *		THIS;
		sint32		RETVAL;
		dXSTARG;

		if (sv_derived_from(ST(0), "NPC")) {
			IV tmp = SvIV((SV*)SvRV(ST(0)));
			THIS = INT2PTR(NPC *,tmp);
		}
		else
			Perl_croak(aTHX_ "THIS is not of type NPC");

		RETVAL = THIS->GetNPCFactionID();
		XSprePUSH; PUSHi((IV)RETVAL);
	}
	XSRETURN(1);
}

XS(XS_NPC_GetPrimaryFaction); /* prototype to pass -Wmissing-prototypes */
XS(XS_NPC_GetPrimaryFaction)
{
	dXSARGS;
	if (items != 1)
		Perl_croak(aTHX_ "Usage: NPC::GetPrimaryFaction(THIS)");
	{
		NPC *		THIS;
		sint32		RETVAL;
		dXSTARG;

		if (sv_derived_from(ST(0), "NPC")) {
			IV tmp = SvIV((SV*)SvRV(ST(0)));
			THIS = INT2PTR(NPC *,tmp);
		}
		else
			Perl_croak(aTHX_ "THIS is not of type NPC");

		RETVAL = THIS->GetPrimaryFaction();
		XSprePUSH; PUSHi((IV)RETVAL);
	}
	XSRETURN(1);
}

XS(XS_NPC_GetIgnoreTarget); /* prototype to pass -Wmissing-prototypes */
XS(XS_NPC_GetIgnoreTarget)
{
	dXSARGS;
	if (items != 1)
		Perl_croak(aTHX_ "Usage: NPC::GetIgnoreTarget(THIS)");
	{
		NPC *		THIS;
		Mob *		RETVAL;

		if (sv_derived_from(ST(0), "NPC")) {
			IV tmp = SvIV((SV*)SvRV(ST(0)));
			THIS = INT2PTR(NPC *,tmp);
		}
		else
			Perl_croak(aTHX_ "THIS is not of type NPC");

		RETVAL = THIS->GetIgnoreTarget();
		ST(0) = sv_newmortal();
		sv_setref_pv(ST(0), "Mob", (void*)RETVAL);
	}
	XSRETURN(1);
}

XS(XS_NPC_SetIgnoreTarget); /* prototype to pass -Wmissing-prototypes */
XS(XS_NPC_SetIgnoreTarget)
{
	dXSARGS;
	if (items != 2)
		Perl_croak(aTHX_ "Usage: NPC::SetIgnoreTarget(THIS, mob)");
	{
		NPC *		THIS;
		Mob*		mob;

		if (sv_derived_from(ST(0), "NPC")) {
			IV tmp = SvIV((SV*)SvRV(ST(0)));
			THIS = INT2PTR(NPC *,tmp);
		}
		else
			Perl_croak(aTHX_ "THIS is not of type NPC");

		if (sv_derived_from(ST(1), "Mob")) {
			IV tmp = SvIV((SV*)SvRV(ST(1)));
			mob = INT2PTR(Mob *,tmp);
		}
		else
			Perl_croak(aTHX_ "mob is not of type Mob");

		THIS->SetIgnoreTarget(mob);
	}
	XSRETURN_EMPTY;
}

XS(XS_NPC_GetNPCHate); /* prototype to pass -Wmissing-prototypes */
XS(XS_NPC_GetNPCHate)
{
	dXSARGS;
	if (items != 2)
		Perl_croak(aTHX_ "Usage: NPC::GetNPCHate(THIS, in_ent)");
	{
		NPC *		THIS;
		sint32		RETVAL;
		dXSTARG;
		Mob*		in_ent;

		if (sv_derived_from(ST(0), "NPC")) {
			IV tmp = SvIV((SV*)SvRV(ST(0)));
			THIS = INT2PTR(NPC *,tmp);
		}
		else
			Perl_croak(aTHX_ "THIS is not of type NPC");

		if (sv_derived_from(ST(1), "Mob")) {
			IV tmp = SvIV((SV*)SvRV(ST(1)));
			in_ent = INT2PTR(Mob *,tmp);
		}
		else
			Perl_croak(aTHX_ "in_ent is not of type Mob");

		RETVAL = THIS->GetNPCHate(in_ent);
		XSprePUSH; PUSHi((IV)RETVAL);
	}
	XSRETURN(1);
}

XS(XS_NPC_IsOnHatelist); /* prototype to pass -Wmissing-prototypes */
XS(XS_NPC_IsOnHatelist)
{
	dXSARGS;
	if (items != 2)
		Perl_croak(aTHX_ "Usage: NPC::IsOnHatelist(THIS, p)");
	{
		NPC *		THIS;
		bool		RETVAL;
		Mob*		p;

		if (sv_derived_from(ST(0), "NPC")) {
			IV tmp = SvIV((SV*)SvRV(ST(0)));
			THIS = INT2PTR(NPC *,tmp);
		}
		else
			Perl_croak(aTHX_ "THIS is not of type NPC");

		if (sv_derived_from(ST(1), "Mob")) {
			IV tmp = SvIV((SV*)SvRV(ST(1)));
			p = INT2PTR(Mob *,tmp);
		}
		else
			Perl_croak(aTHX_ "p is not of type Mob");

		RETVAL = THIS->IsOnHatelist(p);
		ST(0) = boolSV(RETVAL);
		sv_2mortal(ST(0));
	}
	XSRETURN(1);
}

XS(XS_NPC_SetNPCFactionID); /* prototype to pass -Wmissing-prototypes */
XS(XS_NPC_SetNPCFactionID)
{
	dXSARGS;
	if (items != 2)
		Perl_croak(aTHX_ "Usage: NPC::SetNPCFactionID(THIS, in)");
	{
		NPC *		THIS;
		sint32		in = (sint32)SvIV(ST(1));

		if (sv_derived_from(ST(0), "NPC")) {
			IV tmp = SvIV((SV*)SvRV(ST(0)));
			THIS = INT2PTR(NPC *,tmp);
		}
		else
			Perl_croak(aTHX_ "THIS is not of type NPC");

		THIS->SetNPCFactionID(in);
	}
	XSRETURN_EMPTY;
}

XS(XS_NPC_SetFeignMemory); /* prototype to pass -Wmissing-prototypes */
XS(XS_NPC_SetFeignMemory)
{
	dXSARGS;
	if (items != 2)
		Perl_croak(aTHX_ "Usage: NPC::SetFeignMemory(THIS, num)");
	{
		NPC *		THIS;
		char*		num = (char *)SvPV_nolen(ST(1));

		if (sv_derived_from(ST(0), "NPC")) {
			IV tmp = SvIV((SV*)SvRV(ST(0)));
			THIS = INT2PTR(NPC *,tmp);
		}
		else
			Perl_croak(aTHX_ "THIS is not of type NPC");

		THIS->SetFeignMemory(num);
	}
	XSRETURN_EMPTY;
}

XS(XS_NPC_GetFeignMemory); /* prototype to pass -Wmissing-prototypes */
XS(XS_NPC_GetFeignMemory)
{
	dXSARGS;
	if (items != 1)
		Perl_croak(aTHX_ "Usage: NPC::GetFeignMemory(THIS)");
	{
		NPC *		THIS;
		Const_char *		RETVAL;
		dXSTARG;

		if (sv_derived_from(ST(0), "NPC")) {
			IV tmp = SvIV((SV*)SvRV(ST(0)));
			THIS = INT2PTR(NPC *,tmp);
		}
		else
			Perl_croak(aTHX_ "THIS is not of type NPC");

		RETVAL = THIS->GetFeignMemory();
		sv_setpv(TARG, RETVAL); XSprePUSH; PUSHTARG;
	}
	XSRETURN(1);
}

XS(XS_NPC_GetMaxDMG); /* prototype to pass -Wmissing-prototypes */
XS(XS_NPC_GetMaxDMG)
{
	dXSARGS;
	if (items != 1)
		Perl_croak(aTHX_ "Usage: NPC::GetMaxDMG(THIS)");
	{
		NPC *		THIS;
		int16		RETVAL;
		dXSTARG;

		if (sv_derived_from(ST(0), "NPC")) {
			IV tmp = SvIV((SV*)SvRV(ST(0)));
			THIS = INT2PTR(NPC *,tmp);
		}
		else
			Perl_croak(aTHX_ "THIS is not of type NPC");

		RETVAL = THIS->GetMaxDMG();
		XSprePUSH; PUSHu((UV)RETVAL);
	}
	XSRETURN(1);
}

XS(XS_NPC_IsAnimal); /* prototype to pass -Wmissing-prototypes */
XS(XS_NPC_IsAnimal)
{
	dXSARGS;
	if (items != 1)
		Perl_croak(aTHX_ "Usage: NPC::IsAnimal(THIS)");
	{
		NPC *		THIS;
		bool		RETVAL;

		if (sv_derived_from(ST(0), "NPC")) {
			IV tmp = SvIV((SV*)SvRV(ST(0)));
			THIS = INT2PTR(NPC *,tmp);
		}
		else
			Perl_croak(aTHX_ "THIS is not of type NPC");

		RETVAL = THIS->IsAnimal();
		ST(0) = boolSV(RETVAL);
		sv_2mortal(ST(0));
	}
	XSRETURN(1);
}

XS(XS_NPC_GetPetSpellID); /* prototype to pass -Wmissing-prototypes */
XS(XS_NPC_GetPetSpellID)
{
	dXSARGS;
	if (items != 1)
		Perl_croak(aTHX_ "Usage: NPC::GetPetSpellID(THIS)");
	{
		NPC *		THIS;
		int16		RETVAL;
		dXSTARG;

		if (sv_derived_from(ST(0), "NPC")) {
			IV tmp = SvIV((SV*)SvRV(ST(0)));
			THIS = INT2PTR(NPC *,tmp);
		}
		else
			Perl_croak(aTHX_ "THIS is not of type NPC");

		RETVAL = THIS->GetPetSpellID();
		XSprePUSH; PUSHu((UV)RETVAL);
	}
	XSRETURN(1);
}

XS(XS_NPC_SetPetSpellID); /* prototype to pass -Wmissing-prototypes */
XS(XS_NPC_SetPetSpellID)
{
	dXSARGS;
	if (items != 2)
		Perl_croak(aTHX_ "Usage: NPC::SetPetSpellID(THIS, amt)");
	{
		NPC *		THIS;
		int16		amt = (int16)SvUV(ST(1));

		if (sv_derived_from(ST(0), "NPC")) {
			IV tmp = SvIV((SV*)SvRV(ST(0)));
			THIS = INT2PTR(NPC *,tmp);
		}
		else
			Perl_croak(aTHX_ "THIS is not of type NPC");

		THIS->SetPetSpellID(amt);
	}
	XSRETURN_EMPTY;
}

XS(XS_NPC_GetMaxDamage); /* prototype to pass -Wmissing-prototypes */
XS(XS_NPC_GetMaxDamage)
{
	dXSARGS;
	if (items != 2)
		Perl_croak(aTHX_ "Usage: NPC::GetMaxDamage(THIS, tlevel)");
	{
		NPC *		THIS;
		int32		RETVAL;
		dXSTARG;
		int8		tlevel = (int8)SvUV(ST(1));

		if (sv_derived_from(ST(0), "NPC")) {
			IV tmp = SvIV((SV*)SvRV(ST(0)));
			THIS = INT2PTR(NPC *,tmp);
		}
		else
			Perl_croak(aTHX_ "THIS is not of type NPC");

		RETVAL = THIS->GetMaxDamage(tlevel);
		XSprePUSH; PUSHu((UV)RETVAL);
	}
	XSRETURN(1);
}

XS(XS_NPC_SetTaunting); /* prototype to pass -Wmissing-prototypes */
XS(XS_NPC_SetTaunting)
{
	dXSARGS;
	if (items != 2)
		Perl_croak(aTHX_ "Usage: NPC::SetTaunting(THIS, tog)");
	{
		NPC *		THIS;
		bool		tog = (bool)SvTRUE(ST(1));

		if (sv_derived_from(ST(0), "NPC")) {
			IV tmp = SvIV((SV*)SvRV(ST(0)));
			THIS = INT2PTR(NPC *,tmp);
		}
		else
			Perl_croak(aTHX_ "THIS is not of type NPC");

		THIS->SetTaunting(tog);
	}
	XSRETURN_EMPTY;
}

XS(XS_NPC_PickPocket); /* prototype to pass -Wmissing-prototypes */
XS(XS_NPC_PickPocket)
{
	dXSARGS;
	if (items != 2)
		Perl_croak(aTHX_ "Usage: NPC::PickPocket(THIS, thief)");
	{
		NPC *		THIS;
		Client*		thief;

		if (sv_derived_from(ST(0), "NPC")) {
			IV tmp = SvIV((SV*)SvRV(ST(0)));
			THIS = INT2PTR(NPC *,tmp);
		}
		else
			Perl_croak(aTHX_ "THIS is not of type NPC");

		if (sv_derived_from(ST(1), "Client")) {
			IV tmp = SvIV((SV*)SvRV(ST(1)));
			thief = INT2PTR(Client *,tmp);
		}
		else
			Perl_croak(aTHX_ "thief is not of type Client");

		THIS->PickPocket(thief);
	}
	XSRETURN_EMPTY;
}

XS(XS_NPC_StartSwarmTimer); /* prototype to pass -Wmissing-prototypes */
XS(XS_NPC_StartSwarmTimer)
{
	dXSARGS;
	if (items != 2)
		Perl_croak(aTHX_ "Usage: NPC::StartSwarmTimer(THIS, duration)");
	{
		NPC *		THIS;
		int32		duration = (int32)SvUV(ST(1));

		if (sv_derived_from(ST(0), "NPC")) {
			IV tmp = SvIV((SV*)SvRV(ST(0)));
			THIS = INT2PTR(NPC *,tmp);
		}
		else
			Perl_croak(aTHX_ "THIS is not of type NPC");

		THIS->StartSwarmTimer(duration);
	}
	XSRETURN_EMPTY;
}

XS(XS_NPC_DoClassAttacks); /* prototype to pass -Wmissing-prototypes */
XS(XS_NPC_DoClassAttacks)
{
	dXSARGS;
	if (items != 2)
		Perl_croak(aTHX_ "Usage: NPC::DoClassAttacks(THIS, target)");
	{
		NPC *		THIS;
		Mob *		target;

		if (sv_derived_from(ST(0), "NPC")) {
			IV tmp = SvIV((SV*)SvRV(ST(0)));
			THIS = INT2PTR(NPC *,tmp);
		}
		else
			Perl_croak(aTHX_ "THIS is not of type NPC");

		if (sv_derived_from(ST(1), "Mob")) {
			IV tmp = SvIV((SV*)SvRV(ST(1)));
			target = INT2PTR(Mob *,tmp);
		}
		else
			Perl_croak(aTHX_ "target is not of type Mob");

		THIS->DoClassAttacks(target);
	}
	XSRETURN_EMPTY;
}

#ifdef __cplusplus
extern "C"
#endif
XS(boot_NPC); /* prototype to pass -Wmissing-prototypes */
XS(boot_NPC)
{
	dXSARGS;
	char file[256];
	strncpy(file, __FILE__, 256);
	file[255] = 0;
	
	if(items != 1)
		LogFile->write(EQEMuLog::Error, "boot_quest does not take any arguments.");
	char buf[128];

	//add the strcpy stuff to get rid of const warnings....



	XS_VERSION_BOOTCHECK ;

		newXSproto(strcpy(buf, "CheckNPCFactionAlly"), XS_NPC_CheckNPCFactionAlly, file, "$$");
		newXSproto(strcpy(buf, "GetReverseFactionCon"), XS_NPC_GetReverseFactionCon, file, "$$");
		newXSproto(strcpy(buf, "GoToBind"), XS_NPC_GoToBind, file, "$");
		newXSproto(strcpy(buf, "AddItem"), XS_NPC_AddItem, file, "$$$;$");
		newXSproto(strcpy(buf, "AddLootTable"), XS_NPC_AddLootTable, file, "$");
		newXSproto(strcpy(buf, "IsRanger"), XS_NPC_IsRanger, file, "$");
		newXSproto(strcpy(buf, "RemoveItem"), XS_NPC_RemoveItem, file, "$$;$$");
		newXSproto(strcpy(buf, "ClearItemList"), XS_NPC_ClearItemList, file, "$");
		newXSproto(strcpy(buf, "AddCash"), XS_NPC_AddCash, file, "$$$$$");
		newXSproto(strcpy(buf, "RemoveCash"), XS_NPC_RemoveCash, file, "$");
		newXSproto(strcpy(buf, "CountLoot"), XS_NPC_CountLoot, file, "$");
		newXSproto(strcpy(buf, "GetLoottableID"), XS_NPC_GetLoottableID, file, "$");
		newXSproto(strcpy(buf, "SetPetType"), XS_NPC_SetPetType, file, "$$");
		newXSproto(strcpy(buf, "GetCopper"), XS_NPC_GetCopper, file, "$");
		newXSproto(strcpy(buf, "GetSilver"), XS_NPC_GetSilver, file, "$");
		newXSproto(strcpy(buf, "GetGold"), XS_NPC_GetGold, file, "$");
		newXSproto(strcpy(buf, "GetPlatinum"), XS_NPC_GetPlatinum, file, "$");
		newXSproto(strcpy(buf, "SetCopper"), XS_NPC_SetCopper, file, "$$");
		newXSproto(strcpy(buf, "SetSilver"), XS_NPC_SetSilver, file, "$$");
		newXSproto(strcpy(buf, "SetGold"), XS_NPC_SetGold, file, "$$");
		newXSproto(strcpy(buf, "SetPlatinum"), XS_NPC_SetPlatinum, file, "$$");
		newXSproto(strcpy(buf, "SetGrid"), XS_NPC_SetGrid, file, "$$");
		newXSproto(strcpy(buf, "SetSp2"), XS_NPC_SetSp2, file, "$$");
		newXSproto(strcpy(buf, "GetWaypointMax"), XS_NPC_GetWaypointMax, file, "$");
		newXSproto(strcpy(buf, "GetGrid"), XS_NPC_GetGrid, file, "$");
		newXSproto(strcpy(buf, "GetSp2"), XS_NPC_GetSp2, file, "$");
		newXSproto(strcpy(buf, "Depop"), XS_NPC_Depop, file, "$;$");
		newXSproto(strcpy(buf, "Stun"), XS_NPC_Stun, file, "$$");
		newXSproto(strcpy(buf, "IsStunned"), XS_NPC_IsStunned, file, "$");
		newXSproto(strcpy(buf, "IsPVP"), XS_NPC_IsPVP, file, "$");
		newXSproto(strcpy(buf, "CurrentPosition"), XS_NPC_CurrentPosition, file, "$");
		newXSproto(strcpy(buf, "HasBanishCapability"), XS_NPC_HasBanishCapability, file, "$");
		newXSproto(strcpy(buf, "GetNPCFactionID"), XS_NPC_GetNPCFactionID, file, "$");
		newXSproto(strcpy(buf, "GetPrimaryFaction"), XS_NPC_GetPrimaryFaction, file, "$");
		newXSproto(strcpy(buf, "GetIgnoreTarget"), XS_NPC_GetIgnoreTarget, file, "$");
		newXSproto(strcpy(buf, "SetIgnoreTarget"), XS_NPC_SetIgnoreTarget, file, "$$");
		newXSproto(strcpy(buf, "GetNPCHate"), XS_NPC_GetNPCHate, file, "$$");
		newXSproto(strcpy(buf, "IsOnHatelist"), XS_NPC_IsOnHatelist, file, "$$");
		newXSproto(strcpy(buf, "SetNPCFactionID"), XS_NPC_SetNPCFactionID, file, "$$");
		newXSproto(strcpy(buf, "SetFeignMemory"), XS_NPC_SetFeignMemory, file, "$$");
		newXSproto(strcpy(buf, "GetFeignMemory"), XS_NPC_GetFeignMemory, file, "$");
		newXSproto(strcpy(buf, "GetMaxDMG"), XS_NPC_GetMaxDMG, file, "$");
		newXSproto(strcpy(buf, "IsAnimal"), XS_NPC_IsAnimal, file, "$");
		newXSproto(strcpy(buf, "GetPetSpellID"), XS_NPC_GetPetSpellID, file, "$");
		newXSproto(strcpy(buf, "SetPetSpellID"), XS_NPC_SetPetSpellID, file, "$$");
		newXSproto(strcpy(buf, "GetMaxDamage"), XS_NPC_GetMaxDamage, file, "$$");
		newXSproto(strcpy(buf, "SetTaunting"), XS_NPC_SetTaunting, file, "$$");
		newXSproto(strcpy(buf, "PickPocket"), XS_NPC_PickPocket, file, "$$");
		newXSproto(strcpy(buf, "StartSwarmTimer"), XS_NPC_StartSwarmTimer, file, "$$");
		newXSproto(strcpy(buf, "DoClassAttacks"), XS_NPC_DoClassAttacks, file, "$$");
	XSRETURN_YES;
}

#endif //EMBPERL_XS_CLASSES

