//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by EQBuilder.rc
//
#define IDC_ZoomIn                      2
#define IDC_ZoomOut                     3
#define IDC_RESET_VIEW                  4
#define IDC_INCREASE_RES                5
#define IDC_INCREASE_RES2               6
#define IDC_DECREASE_RES                6
#define IDD_EQBUILDER_DIALOG            102
#define IDR_MAINFRAME                   128
#define IDR_MENU1                       132
#define IDD_DATABASE                    134
#define IDD_SQLOPT                      135
#define IDD_BIGZONE                     136
#define IDD_LOOT                        137
#define IDD_FACTIONS                    138
#define IDD_LOADING_MAP                 139
#define IDC_ZONE_COMBO                  1000
#define IDC_ZONE_STATIC                 1002
#define IDC_LOG_STATIC                  1003
#define IDC_ADD_BUTTON                  1004
#define IDC_LOADDB_BUTTON               1005
#define IDC_COMPILE_BUTTON              1006
#define IDC_WRITE_BUTTON                1007
#define IDC_RELOAD_MAP                  1008
#define IDC_ADD_DIR_BUTTON              1009
#define IDC_COMPILE_ALL_BUTTON          1010
#define IDC_STATS_STATIC                1015
#define ID_STATIC                       1018
#define ID_STATIC2                      1019
#define IDC_CPS_TREE                    1021
#define IDC_MOB_TREE                    1021
#define IDC_SPAWN_TREE                  1022
#define IDC_MOVING_CHECK                1025
#define IDC_AROUND_EDIT                 1028
#define IDC_AROUND_CHECK                1029
#define IDC_DOOR_BUTTON                 1030
#define IDC_AFFIRM_CHECK                1030
#define IDC_AFFIRM_EDIT                 1031
#define IDC_NPC_BUTTON                  1032
#define IDC_CAMP_CHECK                  1032
#define IDC_TELEPORT_BUTTON             1033
#define IDC_CAMP_EDIT                   1033
#define IDC_SPAWN_BUTTON                1034
#define IDC_DELTAZ_CHECK                1034
#define IDC_NPC_STATIC                  1035
#define IDC_MOB_STATIC                  1036
#define IDC_SPAWN_STATIC                1037
#define IDC_DOOR_STATIC                 1038
#define IDC_TELEPORT_STATIC             1039
#define IDC_LOG_TREE                    1040
#define IDC_DELTAZ_EDIT                 1041
#define IDC_PROGRESS                    1043
#define IDC_SQL_RADIO                   1044
#define IDC_DATABASE_RADIO              1045
#define IDC_MINPROB_CHECK               1046
#define IDC_MINPROB_EDIT                1047
#define IDC_MOVED_CHECK                 1051
#define IDC_DEAD_CHECK                  1052
#define IDC_OCCUR_CHECK                 1053
#define IDC_DELETE_BUTTON               1055
#define IDC_MOVED_EDIT                  1056
#define IDC_DEAD_EDIT                   1057
#define IDC_OCCUR_EDIT                  1058
#define IDC_TYPELOG_COMBO               1059
#define IDC_GRID_STATIC                 1060
#define IDC_DELETE_CHECK                1061
#define IDC_MERCHANT_STATIC             1061
#define IDC_PROCESS_BUTTON              1062
#define IDC_GRID_BUTTON                 1063
#define IDC_DELETE_ALL_BUTTON           1063
#define IDC_HOST                        1064
#define IDC_USER                        1065
#define IDC_PASSWORD                    1066
#define IDC_DATABASE                    1067
#define IDC_GRIDID                      1072
#define IDC_USESPECID                   1074
#define IDC_NPCID                       1075
#define IDC_SPAWNID                     1079
#define IDC_USEZONEID                   1082
#define IDC_ZONEID                      1083
#define IDC_USEDBID                     1087
#define IDC_OUT_NPCS                    1088
#define IDC_OUT_SPAWNS                  1089
#define IDC_OUT_DOORS                   1090
#define IDC_OUT_TELEPORTS               1091
#define IDC_OUT_GRIDS                   1092
#define IDC_OUT_MERCHANTS               1093
#define IDC_DATAMODE                    1094
#define IDC_ZONEVIEW                    1099
#define IDC_ZONE_ZOOM_IN                1101
#define IDC_ZONE_ZOOM_OUT               1102
#define IDC_ZONE_RESET                  1103
#define IDC_ZONE_BIG                    1104
#define IDC_REPROCESS                   1105
#define IDC_EQMAPS                      1107
#define IDC_BrowseMaps                  1108
#define IDC_DRAW_PATHS                  1109
#define IDC_EQEMUMAPS                   1109
#define IDC_BrowseEmuMaps               1110
#define IDC_DELETE_MAPPING              1112
#define IDC_ADD_MAPPING                 1113
#define IDC_TOGGLE_FACTIONS             1114
#define IDC_EDIT_MAPPING                1114
#define IDC_FACTIONS_BUTTON             1115
#define IDC_EDIT_MAPPINGS               1115
#define IDC_LOOT_BUTTON                 1116
#define IDC_TOGGLE_LOOT                 1116
#define IDC_SPELLS_BUTTON               1117
#define IDC_SOURCE_MAPPINGS             1117
#define IDC_CURRENT_MAPPINGS            1118
#define IDC_GO_BUTTON                   1120
#define ID_DATABASE_CONNECTION          32771
#define ID_OUTPUT_SQLOPT                32772
#define ID_OUTPUT_DBOPT                 32773

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        140
#define _APS_NEXT_COMMAND_VALUE         32774
#define _APS_NEXT_CONTROL_VALUE         1121
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
