#simple root level makefile by Father Nitwit

all:
	gmake -C EMuShareMem
	gmake -C world
	gmake -C zone
	gmake -C utils

clean:
	gmake -C EMuShareMem clean
	gmake -C world clean
	gmake -C zone clean
	gmake -C utils clean

